### ISSUE TITLE
Instead of editing just one word, any other matching text is affected

### ISSUE THREAD

**Issue by ethanribeiro** [carmo-evan/mattermost-plugin-replace#5] opened 2019-05-29 20:13 UTC
This is different from the way `sed` works. For the input string `what if you typ the word typical`, `sed 's/typ/type/'` will output `what if you type the word typical`. The plugin outputs `what if you type the word typeical`.

**Comment by jasonblais** [comment] 2019-05-30 15:43
@ethanribeiro do you mean that only words that fully match the text `typ` are replaced? 

E.g. if I posted, `typ the word typ`, then `s/typ/type`, the post would update to `type the word type`. But with your example, `typical` should not get updated because it's not an exact match to `typ`

**Comment by carmo-evan** [comment] 2019-05-30 21:13
@jasonblais I've confirmed the issue.

### Current Behavior
- input: `what if you typ the word typical`, then `s/typ/type`
- output: `what if you type the word typeical`

### Desired Behavior
- output : `what if you type the word typical`

We want the plugin to match only full words, not parts of words. Will work on a fix.

**Comment by carmo-evan** [comment] 2019-05-30 21:47
@jasonblais this is ready for verification in v0.2.0.

**Comment by jasonblais** [comment] 2019-05-31 02:41
Confirmed, resolved in v0.2.0

**Closed as completed** 2019-06-01 12:08 UTC
Labels: bug, v0.2.0
